# Generated by Django 3.1.6 on 2021-02-15 16:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Member1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('first_name', models.CharField(max_length=120)),
                ('middle_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('age', models.CharField(max_length=120)),
                ('dob', models.DateField()),
                ('mob_no', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=120)),
                ('pin_code', models.CharField(max_length=120)),
                ('comment', models.CharField(max_length=120)),
                ('email_id', models.EmailField(max_length=254)),
                ('test', models.CharField(max_length=120)),
                ('total_amount', models.CharField(max_length=120)),
                ('overall_discount', models.CharField(max_length=120)),
                ('gross_amount', models.CharField(max_length=120)),
                ('discount_amount', models.CharField(max_length=120)),
                ('net_amount', models.CharField(max_length=120)),
                ('due_amount', models.CharField(max_length=120)),
                ('cash_amount', models.CharField(max_length=120)),
                ('paid_amount', models.CharField(max_length=120)),
                ('payment_getway', models.CharField(choices=[('Cash', 'Cash'), ('CreditCard', 'CreditCard'), ('DebitCard', 'DebitCard'), ('Cheque', 'Cheque'), ('Paytm', 'Paytm'), ('Neft', 'Neft')], max_length=128)),
                ('remark', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Add_Member2',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('reg_no', models.CharField(editable=False, max_length=100)),
                ('title', models.CharField(choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Miss', 'Miss'), ('Baby of', 'Baby of'), ('Baba of', 'Baba of'), ('Dr Mr', 'Dr Mr'), ('Dr Mrs', 'Dr Mrs'), ('Dr Miss', 'Dr Miss')], max_length=128)),
                ('first_name', models.CharField(max_length=120)),
                ('middle_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=128)),
                ('email_id', models.EmailField(max_length=254)),
                ('dob', models.DateField()),
                ('age', models.CharField(max_length=120)),
                ('mob_no', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=120)),
                ('pin_code', models.CharField(max_length=120)),
                ('date_Of_Enrollment', models.DateField()),
                ('blood_group', models.CharField(choices=[('A +ve', 'A +ve'), ('A -ve', 'A -ve'), ('B +ve', 'B +ve'), ('B -ve', 'B -ve'), ('O +ve', 'O +ve'), ('O -ve', 'O -ve')], max_length=128)),
                ('marital_status', models.CharField(choices=[('Married', 'Married'), ('UnMarried', 'UnMarried')], max_length=128)),
                ('wedding_aniversary_date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('house_hold_status', models.CharField(choices=[('Nuclear', 'Nuclear'), ('Joint', 'Joint')], max_length=128)),
                ('income_level', models.CharField(choices=[('Lower', 'Lower'), ('Middle', 'Middle'), ('Upper', 'Upper'), ('HNI', 'HNI')], max_length=128)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('occupation', models.CharField(choices=[('Worker', 'Worker'), ('Student', 'Student'), ('Farming', 'Farming'), ('Sales Job', 'Sales Job'), ('HouseWife', 'HouseWife'), ('Businessman', 'Businessman'), ('Professional Job', 'Professional Job'), ('Mangerial Job', 'Mangerial Job'), ('Office Desk', 'Office Desk'), ('Key Management', 'Key Management')], max_length=128)),
                ('community', models.CharField(choices=[('CTL Employee', 'CTL Employee'), ('CTL Family', 'CTL Family'), ('CTL Vendor', 'CTL Vendor'), ('GSB', 'GSB'), ('Airoli Society', 'Airoli Society')], max_length=128)),
                ('religion', models.CharField(choices=[('Hindu', 'Hindu'), ('Muslim', 'Muslim'), ('Christian', 'Christian'), ('Parsi', 'Parsi'), ('Buddhist', 'Buddhist'), ('Jain', 'Jain'), ('Other', 'Other')], max_length=128)),
                ('family_relationship', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
