# Generated by Django 3.1.1 on 2020-12-13 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job_Openings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=70)),
                ('job_type', models.CharField(choices=[('fulltime', 'fulltime'), ('parttime', 'parttime'), ('temporary', 'temporary'), ('remotework', 'remotework'), ('internship', 'internship')], max_length=128)),
                ('qualification', models.CharField(max_length=70)),
                ('skill_sets', models.CharField(max_length=70)),
                ('certifications', models.CharField(max_length=70)),
                ('annualsalary_lacs', models.CharField(choices=[('1lakh', '1lakh'), ('2lakh', '2lakh'), ('3lakh', '3lakh'), ('4lakh', '4lakh'), ('5lakh', '5lakh'), ('6lakh', '6lakh'), ('7lakh', '7lakh'), ('8lakh', '8lakh'), ('9lakh', '9lakh'), ('10lakh', '10lakh')], max_length=128)),
                ('annualsalary_thousands', models.CharField(choices=[('10Thousand', '10Thousand'), ('20Thousand', '20Thousand'), ('30Thousand', '30Thousand'), ('40Thousand', '40Thousand'), ('50Thousand', '50Thousand')], max_length=128)),
                ('other_remark', models.CharField(max_length=70)),
                ('locations', models.CharField(max_length=70)),
                ('college_preference', models.CharField(max_length=70)),
                ('joining_priod', models.CharField(choices=[('fulltime1', 'fulltime1'), ('parttime1', 'parttime1')], max_length=70)),
                ('experience_year', models.CharField(choices=[('1yr', '1yr'), ('1yr', '2yrs'), ('3yrs', '3yrs'), ('4yrs', '4yrs'), ('5yr', '5yr')], max_length=128)),
                ('experience_months', models.CharField(choices=[('1month', '1month'), ('2months', '2months'), ('3months', '3months'), ('4months', '4months'), ('5months', '5months'), ('6months', '6months')], max_length=128)),
                ('NoOf_Vacancy', models.IntegerField(max_length=10)),
                ('job_description', models.CharField(max_length=70)),
                ('job_responsibilty', models.CharField(max_length=70)),
            ],
        ),
    ]
