# Generated by Django 3.1.1 on 2020-12-13 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_openings',
            name='NoOf_Vacancy',
            field=models.IntegerField(),
        ),
    ]
