# Generated by Django 3.1.1 on 2020-12-22 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0002_auto_20201213_2329'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply_job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=70)),
                ('Last_name', models.CharField(max_length=70)),
                ('Email_id', models.EmailField(max_length=254)),
                ('Mobile_no', models.IntegerField()),
                ('Gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], max_length=128)),
                ('Date_of_Birth', models.DateField()),
                ('Curent_Loaction', models.CharField(max_length=70)),
                ('Total_Exp_Year', models.IntegerField()),
                ('Total_Exp_Month', models.IntegerField()),
                ('Upload_cv', models.FileField(blank=True, upload_to='post_image')),
                ('jobop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app4.job_openings')),
            ],
        ),
    ]
