# Generated by Django 3.1.1 on 2020-12-30 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0004_auto_20201225_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply_job',
            name='Upload_cv',
            field=models.FileField(blank=True, upload_to='pot_image/'),
        ),
    ]
