# Generated by Django 3.1.4 on 2020-12-30 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0005_auto_20201230_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply_job',
            name='Upload_cv',
            field=models.FileField(blank=True, upload_to='post_image/'),
        ),
    ]
